 function chkinput1(form)
    {
        if(form.email.value=="")
        {
            alert("电子邮箱不能为空!");
            form.email.select();
            return(false);
        }
        if(form.email.value.indexOf('@')<0)
        {
            alert("电子邮箱输入错误!");
            form.email.select();
            return(false);
        }
        if(form.truename.value=="")
        {
            alert("真实姓名不能为空!");
            form.truename.select();
            return(false);
        }
        if(form.sfzh.value=="")
        {
            alert("身份证号不能为空!");
            form.sfzh.select();
            return(false);
        }
        if(form.tel.value=="")
        {
            alert("联系电话不能为空!");
            form.tel.select();
            return(false);
        }
        if(form.dizhi.value=="")
        {
            alert("联系地址不能为空!");
            form.dizhi.select();
            return(false);
        }

        return(true);
    }
